# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check-win:
    runs-on: windows-latest
    name: windows-latest
    strategy:
      fail-fast: false
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v2
      
      - uses: r-lib/actions/setup-r@v2
      
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          extra-packages: any::rcmdcheck
          
      - uses: r-lib/actions/setup-pandoc@v1
    
      - name: Install windows dependencies
        run: |
          msys2 -c 'cp -f pacman.conf /etc/pacman.conf'
          msys2 -c 'pacman --noconfirm -Syyuu'
          msys2 -c 'pacman --noconfirm -Suu'
          msys2 -c 'pacman --noconfirm -S mingw-w64-x86_64-hdf5'
          msys2 -c 'pacman --noconfirm -S mingw-w64-x86_64-proj'
          msys2 -c 'pacman --noconfirm -S mingw-w64-x86_64-pkg-config'
          msys2 -c '/mingw64/bin/pkg-config.exe --cflags proj'
          msys2 -c 'ls /'
          msys2 -c 'pkg-config.exe --cflags proj'

